### ISSUE TITLE
GSM461180 fastqs

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-novice-tutorial#7]
@alexiswl - Do we need to download fastqs for GSM461180?

Don't think we use it in the main workflow unless it's referred else where?

**Comment by alexiswl** [comment]
Fastqs to be downloaded - https://umccr.github.io/cwl-novice-tutorial/#downloading-sample-and-reference-data

**Comment by alexiswl** [comment]
And then these files are used here - https://umccr.github.io/cwl-novice-tutorial/#downloading-sample-and-reference-data

**Comment by alexiswl** [comment]
And then again here - https://umccr.github.io/cwl-novice-tutorial/03-dependency_graphs.html#multi-step-workflow

**Comment by skanwal** [comment]
This workflow input json is using `GSM461177` - I don't see it referring to `GSM461180`.

**Comment by skanwal** [comment]
I want to remove it from download section - unless I have missed anything.
